version: '3.7'

services:
  web:
    build:
      context: .
    command: >
            sh -c "gunicorn locallibrary.wsgi:application --bind 0.0.0.0:8000 &&
                   python3 manage.py makemigrations &&
                   python3 manage.py migrate "
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=locallibrary
      - POSTGRES_USER=locallibrary
      - POSTGRES_NAME=locallibrary
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - web

volumes:
  static_volume:
  db_data: