version: "3.9"

services:
  openssl:
    build:
      context: .
      target: openssl
    container_name: openssl
    volumes:
      - cert_volume:/certs


  app-build:
    build:
      context: .
      target: build
    container_name: app-build
    volumes:
      - dependencies:/dependencies
      - ./static:/usr/share/nginx/html
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
      - cert_volume:/certs:ro

  app-prod:
    build:
      context: .
      target: app
    container_name: app-prod
    depends_on:
      - app-build
    restart: unless-stopped
    ports:
      - "7070:80"
      - "443:443"
    volumes:
      - dependencies:/dependencies
      - ./static:/usr/share/nginx/html
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
      - cert_volume:/certs:ro


volumes:
  cert_volume:
